CREATE TABLE IF NOT EXISTS CAMEL_FILEPROCESSED  (processorName VARCHAR(255), digest VARCHAR(255), fileName varchar(255),createdAt TIMESTAMP);
--CREATE UNIQUE INDEX IF NOT EXISTS  CAMEL_FILEPROCESSED_UNIQUE_DIGEST_IDX ON CAMEL_FILEPROCESSED (processorName,digest); CREATE INDEX IF NOT EXISTS NOT SUPPORTED in 9.4, requires postgres 9.5..
--CREATE UNIQUE INDEX IF NOT EXISTS  CAMEL_FILEPROCESSED_UNIQUE_NAME_IDX ON CAMEL_FILEPROCESSED (processorName,fileName);
