version: 2.1
orbs:
  docker: circleci/docker@0.5.20
  slack: circleci/slack@2.2.0
executors:
  cci-toolbox-java11:
    docker:
      - image: eu.gcr.io/entur-system-1287/circleci-toolbox-image-java11
        auth:
          username: _json_key
          password: $DOCKER_PASSWORD
    environment:
      DEBIAN_FRONTEND: "noninteractive"
      MAVEN_OPTS: -Xmx3G

  entur-cci-toolbox:
    docker:
      - image: entur/cci-toolbox:2.0

aliases:
  - &GCP-auth
    name: GCP Authentication for Google Cloud Deploy
    command: |
      echo $GCLOUD_SERVICE_KEY > ${HOME}/account-auth.json
      gcloud auth activate-service-account --key-file ${HOME}/account-auth.json
      gcloud beta container clusters get-credentials $CLOUDSDK_CONTAINER_CLUSTER --region $CLOUDSDK_COMPUTE_ZONE --project $CLOUDSDK_CORE_PROJECT

  - &docker-login
    name: Docker login
    command: |
      docker login -u _json_key --password-stdin https://eu.gcr.io \<<< "${DOCKER_PASSWORD}"

  - &get-new-image-version
    name: Getting release version from app_version file
    command: |
      echo "export APP_VERSION=$(cat ./gcr.image.version)" >> $BASH_ENV

  - &update-helm-chart
    name: Set version in helm dir to $APP_VERSION
    command: |
      echo "Setting helm versions to $APP_VERSION"
      pushd helm/marduk
      sed -i "s/version:.*$/version: '$APP_VERSION'/g"  ./Chart.yaml
      sed -i "s/appVersion:.*$/appVersion: '$APP_VERSION'/g"  ./Chart.yaml
      popd

  - &team-ror-circleci-slackhook
      https://hooks.slack.com/services/${SLACK_API_KEY_CIRCLE_CI}

  - &team-ror-releases-slackhook
      https://hooks.slack.com/services/${SLACK_API_KEY_RELEASES}

  - &deploy-payload
      "*Ready to Deploy*: <$CIRCLE_BUILD_URL|$CIRCLE_PROJECT_REPONAME #$CIRCLE_PREVIOUS_BUILD_NUM> to *$NAMESPACE*\n
      Repository: <https://circleci.com/bb/enturas/workflows/$CIRCLE_PROJECT_REPONAME|$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME>\n
      Branch: <https://circleci.com/bb/enturas/$CIRCLE_PROJECT_REPONAME/tree/$CIRCLE_BRANCH|$CIRCLE_BRANCH>\n
      Version: $APP_VERSION \n
      User: $CIRCLE_USERNAME"

  - &success-payload
      ":tada: Job $CIRCLE_STAGE has succeeded!\n
   Version: $APP_VERSION \n
   User: $CIRCLE_USERNAME"

  - &failure-payload
      ":red_circle: Job $CIRCLE_STAGE has failed!\n
   Version: $APP_VERSION \n
   User: $CIRCLE_USERNAME"

commands:
  save-image-name:
    parameters:
      image-version:
        type: string
        default: $BRANCH_IMAGE_NAME-SNAPSHOT
    steps:
      - run:
          command: echo "$CIRCLE_BRANCH-v$CIRCLE_BUILD_NUM-$(echo -n $CIRCLE_SHA1 | tail -c 8)" > ./gcr.image.version
      - persist_to_workspace:
          root: .
          paths: ./gcr.image.version
  slack-status:
    parameters:
      success_payload:
        type: string
        default: *success-payload
    steps:
      - attach_workspace:
          at: .
      - run: *get-new-image-version
      - slack/status:
          webhook: *team-ror-circleci-slackhook
          success_message: << parameters.success_payload >>
          failure_message: *failure-payload

jobs:
  build:
    executor: cci-toolbox-java11
    steps:
      - checkout
      - restore_cache:
          key: dep-cache-{{ checksum "pom.xml" }}
      - run: mvn org.apache.maven.plugins:maven-dependency-plugin:3.1.0:go-offline -s /tools/m2/settings.xml
      - save_cache:
          paths:
            - ~/.m2
          key: dep-cache-{{ checksum "pom.xml" }}
      # Cannot use -o because of snapshot dependencies.
      - run: mvn verify -s /tools/m2/settings.xml
      - run:
          name: Save test results
          command: |
            mkdir -p ~/junit/
            find . -type f -regex ".*/target/surefire-reports/.*xml" -exec cp {} ~/junit/ \;
            find . -type f -regex ".*/target/surefire-reports/.*dumpstream" -exec cp {} ~/junit/ \;
            find . -type f -regex ".*/target/surefire-reports/.*log" -exec cp {} ~/junit/ \;
          when: always
      - store_test_results:
          path: ~/junit
      - store_artifacts:
          path: ~/junit
      - persist_to_workspace:
          root: ~/project
          paths:
            - target
            - Dockerfile
            - .circleci

  deploy-docker:
    executor: entur-cci-toolbox
    steps:
      - attach_workspace:
          at: ~/project
      - setup_remote_docker:
          docker_layer_caching: true
      - run: *docker-login
      - docker/build:
          image: marduk
          tag: $CIRCLE_BRANCH-v$CIRCLE_BUILD_NUM-$(echo -n $CIRCLE_SHA1 | tail -c 8)
          registry: eu.gcr.io/entur-system-1287
      - docker/push:
          image: marduk
          tag: $CIRCLE_BRANCH-v$CIRCLE_BUILD_NUM-$(echo -n $CIRCLE_SHA1 | tail -c 8)
          registry: eu.gcr.io/entur-system-1287

  deploy-helm:
    executor: entur-cci-toolbox
    steps:
      - checkout
      - attach_workspace:
          at: ~/project
      - run: *get-new-image-version
      - run: *update-helm-chart
      - run: *GCP-auth
      - run:
          name: Deploy Helm chart to Kubernetes
          command: helm upgrade --install marduk ./helm/marduk --values=./helm/marduk/values.yaml --values=./helm/marduk/$NAMESPACE-values.yaml --namespace=$NAMESPACE
      - slack-status
  slack-approval:
    executor: slack/alpine
    steps:
      - attach_workspace:
          at: ~/project
      - run: *get-new-image-version
      - slack/approval:
          webhook: *team-ror-releases-slackhook
          message: *deploy-payload

workflows:
  version: 2.1
  build_test_deploy:
    jobs:
      - build:
          name: build-release
          context: dev
      -  deploy-docker:
           name: push-release
           context: dev
           requires:
             - build-release
           post-steps:
             - save-image-name
           filters:
             branches:
               only: master
      - deploy-helm:
          name: deploy-dev-release
          context: dev
          requires:
            - push-release
      - slack-approval:
          name: staging-deploy-message-release
          context: stage
          requires:
            - deploy-dev-release
      - approve-staging-release:
          type: approval
          requires:
            - staging-deploy-message-release
      - deploy-helm:
          name: deploy-staging-release
          context: stage
          requires:
            - approve-staging-release
      - slack-approval:
          name: production-deploy-message-release
          context: production
          requires:
            - deploy-staging-release
      - approve-production-release:
          type: approval
          requires:
            - production-deploy-message-release
      - deploy-helm:
          name: deploy-production-release
          context: production
          requires:
            - approve-production-release