env: dev
replicas: 2

gcp:
  blobstoreProjectId: entur-ror-dev
  pubsubProjectId: entur-ror-dev
  databaseInstance: entur-ror-dev:europe-west1:marduk-db-pg13=tcp:5432
  bucketName: marduk-dev
  exchangeBucketName: ror-marduk-exchange-dev
  otpReportBucketName: otpreport.dev.entur.org
  otpGraphBucketName: ror-otp-graphs-dev
  nisabaExchangeBucketName: ror-nisaba-exchange-dev

chouette:
  service: http://chouette.dev.entur.internal
  validateLevel1CronSchedule: 0+55+23+?+*+MON-FRI
  refreshStatsCacheCronSchedule: 0+0/10+2-22+*+*+?
  gtfsExport: false
  enablePreValidation: false
  enablePostValidation: false

baba:
  service: http://baba.dev.entur.internal

duplicateFileFilter:
  webFilter: true

netex:
  export: tiamat/CurrentAndFuture_latest.zip

osm:
  fetchCronSchedule: 0+11+*+*+*+?

google:
  publish:
    autoStartup: false
    cronSchedule: 0+0+4+?+*+*
  publishQA:
    autoStartup: false
    cronSchedule: 0+30+4+?+*+*
    includeShapes: true

auth0:
  partner:
    url: https://partner.dev.entur.org
    audience: https://api.dev.entur.io
    administratorAccessEnabled: true
  ror:
    url: https://ror-entur-dev.eu.auth0.com
    audience: https://ror.api.dev.entur.io

oauth2:
  client:
    id: tug4poFyfcqFSXYvJOn7yZCl5FFbIxQM
    url: https://ror-entur-dev.eu.auth0.com/oauth/token
    audience: https://ror.api.dev.entur.io

monitoringEnabled: true
