env: dev
replicas: 2
gcpProjectId: carbon-1287
gcpDatabaseInstance: carbon-1287:europe-west1:marduk-db-1=tcp:5432
gcpKeyName: marduk-carbon-storage-key
gcpExchangeKeyName: marduk-exchange-carbon-storage-key
gcpBucketName: marduk
gcpExchangeBucketName: marduk-exchange
gcpOtpReportBucketName: otpreport-test.entur.org

chouette:
  validateLevel1CronSchedule: 0+30+23+?+*+MON-FRI

osm:
  fetchCronSchedule: 0+11+*+*+*+?

google:
  publish:
    autoStartup: false
    cronSchedule: 0+0+4+?+*+*
  publishQA:
    autoStartup: false
    cronSchedule: 0+30+4+?+*+*
    includeShapes: true



keycloakUrl: https://kc-dev.devstage.entur.io/auth
auth0:
  url: https://partner.dev.entur.org
  audience: https://api.dev.entur.io
  administratorAccessEnabled: true

resources:
  cpuLimit: "3"
  memLimit: 9000Mi
  cpuRequest: "1"
  memRequest: 7000Mi
  xmx: 5g

monitoringEnabled: true
