env: dev
replicas: 2

gcp:
  blobstoreProjectId: entur-ror-dev
  pubsubProjectId: entur-ror-dev
  databaseInstance: entur-ror-dev:europe-west1:marduk-db-1=tcp:5432
  bucketName: marduk-dev
  exchangeBucketName: ror-marduk-exchange-dev
  otpReportBucketName: otpreport.dev.entur.org
  otpGraphBucketName: ror-otp-graphs-dev
  nisabaExchangeBucketName: ror-nisaba-exchange-dev

chouette:
  validateLevel1CronSchedule: 0+30+23+?+*+MON-FRI
  refreshStatsCacheCronSchedule: 0+0/10+2-22+*+*+?

osm:
  fetchCronSchedule: 0+11+*+*+*+?

google:
  publish:
    autoStartup: false
    cronSchedule: 0+0+4+?+*+*
  publishQA:
    autoStartup: false
    cronSchedule: 0+30+4+?+*+*
    includeShapes: true

keycloak:
  url: https://kc-dev.devstage.entur.io/auth

auth0:
  partner:
    url: https://partner.dev.entur.org
    audience: https://api.dev.entur.io
    administratorAccessEnabled: true
  ror:
    url: https://ror-entur-dev.eu.auth0.com
    audience: https://ror.api.dev.entur.io

oauth2:
  client:
    id: tug4poFyfcqFSXYvJOn7yZCl5FFbIxQM
    url: https://ror-entur-dev.eu.auth0.com/oauth/token
    audience: https://ror.api.dev.entur.io

ingress:
  loadBalancerIP: 35.205.170.68

monitoringEnabled: true
