env: production
replicas: 2

gcp:
  blobstoreProjectId: neon-1287
  pubsubProjectId: neon-1287
  databaseInstance: entur-ror-prod:europe-west1:marduk-db-1=tcp:5432
  bucketName: marduk-production
  exchangeBucketName: marduk-exchange-production
  otpReportBucketName: otpreport.entur.org

chouette:
  validateLevel1CronSchedule: 0+30+23+?+*+*

osm:
  fetchCronSchedule: 0+11+*+*+*+?

google:
  publish:
    autoStartup: true
    cronSchedule: 0+0+4+?+*+*
  publishQA:
    autoStartup: true
    cronSchedule: 0+30+4+?+*+*
    includeShapes: false

keycloakUrl: https://auth.entur.org/auth
auth0:
  url: https://partner.entur.org
  audience: https://api.entur.io
  administratorAccessEnabled: false

ingress:
  loadBalancerIP: 35.205.233.237

resources:
  cpuLimit: "3"
  memLimit: 9000Mi
  cpuRequest: "2"
  memRequest: 7000Mi
  xmx: 5g

monitoringEnabled: false
