env: production
replicas: 2

gcp:
  blobstoreProjectId: entur-ror-prod
  pubsubProjectId: entur-ror-prod
  databaseInstance: entur-ror-prod:europe-west1:marduk-db-1=tcp:5432
  bucketName: marduk-production
  exchangeBucketName: ror-marduk-exchange-production
  otpReportBucketName: otpreport.entur.org
  otpGraphBucketName: ror-otp-graphs-production

chouette:
  validateLevel1CronSchedule: 0+30+23+?+*+*
  refreshStatsCacheCronSchedule: 0+0/10+2-22+*+*+?

osm:
  fetchCronSchedule: 0+11+*+*+*+?

google:
  publish:
    autoStartup: true
    cronSchedule: 0+0+4+?+*+*
  publishQA:
    autoStartup: true
    cronSchedule: 0+30+4+?+*+*
    includeShapes: false

keycloak:
  url: https://auth.entur.org/auth

auth0:
  partner:
    url: https://partner.entur.org
    audience: https://api.entur.io
    administratorAccessEnabled: false
  ror:
    url: https://ror-entur.eu.auth0.com
    audience: https://ror.api.entur.io

oauth2:
  client:
    id: marduk
    url: https://auth.entur.org/auth/realms/rutebanken/protocol/openid-connect/token
    audience: account


ingress:
  loadBalancerIP: 35.205.233.237

monitoringEnabled: false
