env: production
replicas: 2
gcpProjectId: neon-1287
gcpDatabaseInstance: neon-1287:europe-west1:marduk-db-1=tcp:5432
gcpKeyName: marduk-neon-storage-key
gcpExchangeKeyName: marduk-exchange-neon-storage-key
gcpBucketName: marduk-production
gcpExchangeBucketName: marduk-exchange-production
gcpOtpReportBucketName: otpreport.entur.org

chouette:
  validateLevel1CronSchedule: 0+30+23+?+*+*

osm:
  fetchCronSchedule: 0+11+*+*+*+?

google:
  publish:
    autoStartup: true
    cronSchedule: 0+0+4+?+*+*
  publishQA:
    autoStartup: true
    cronSchedule: 0+30+4+?+*+*
    includeShapes: false

keycloakUrl: https://auth.entur.org/auth
auth0:
  url: https://partner.entur.org
  audience: https://api.entur.io
  administratorAccessEnabled: false

resources:
  cpuLimit: "4"
  memLimit: 14000Mi
  cpuRequest: "2"
  memRequest: 12000Mi
  xmx: 10g

monitoringEnabled: false
