env: staging
replicas: 2

gcp:
  blobstoreProjectId: entur-ror-test
  pubsubProjectId: entur-ror-test
  databaseInstance: entur-ror-test:europe-west1:marduk-db-1=tcp:5432
  bucketName: marduk-test
  exchangeBucketName: ror-marduk-exchange-test
  otpReportBucketName: otpreport.staging.entur.org
  otpGraphBucketName: ror-otp-graphs-test

chouette:
  validateLevel1CronSchedule: 0+30+4+?+*+*
  refreshStatsCacheCronSchedule: 0+0/10+7-23+*+*+?

osm:
  fetchCronSchedule: 0+11+*+*+*+?

google:
  publish:
    autoStartup: false
    cronSchedule: 0+0+4+?+*+*
  publishQA:
    autoStartup: false
    cronSchedule: 0+30+4+?+*+*
    includeShapes: false

keycloakUrl: https://kc-stage.devstage.entur.io/auth
auth0:
  url: https://partner.staging.entur.org
  audience: https://api.staging.entur.io
  administratorAccessEnabled: false

ingress:
  loadBalancerIP: 130.211.80.129

monitoringEnabled: true
