env: staging
replicas: 2

gcp:
  blobstoreProjectId: radon-1287
  pubsubProjectId: radon-1287
  databaseInstance: radon-1287:europe-west1:marduk-db-1=tcp:5432
  bucketName: marduk-stage
  exchangeBucketName: marduk-exchange-stage
  otpReportBucketName: otpreport-stage.entur.org

chouette:
  validateLevel1CronSchedule: 0+30+4+?+*+*

osm:
  fetchCronSchedule: 0+11+*+*+*+?

google:
  publish:
    autoStartup: false
    cronSchedule: 0+0+4+?+*+*
  publishQA:
    autoStartup: false
    cronSchedule: 0+30+4+?+*+*
    includeShapes: false

keycloakUrl: https://kc-stage.devstage.entur.io/auth
auth0:
  url: https://partner.staging.entur.org
  audience: https://api.staging.entur.io
  administratorAccessEnabled: false

resources:
  cpuLimit: "3"
  memLimit: 11000Mi
  cpuRequest: "2"
  memRequest: 9000Mi
  xmx: 7g

monitoringEnabled: true
