env: staging
replicas: 2
gcpProjectId: radon-1287
gcpDatabaseInstance: radon-1287:europe-west1:marduk-db-1=tcp:5432
gcpKeyName: marduk-radon-storage-key
gcpExchangeKeyName: marduk-exchange-radon-storage-key
gcpBucketName: marduk-stage
gcpExchangeBucketName: marduk-exchange-stage
gcpOtpReportBucketName: otpreport-stage.entur.org

chouette:
  validateLevel1CronSchedule: 0+45+2+?+*+*

osm:
  fetchCronSchedule: 0+11+*+*+*+?

google:
  publish:
    autoStartup: false
    cronSchedule: 0+0+4+?+*+*
  publishQA:
    autoStartup: false
    cronSchedule: 0+30+4+?+*+*
    includeShapes: false

keycloakUrl: https://kc-stage.devstage.entur.io/auth
auth0:
  url: https://partner.staging.entur.org
  audience: https://api.staging.entur.io
  administratorAccessEnabled: false

resources:
  cpuLimit: "4"
  memLimit: 14000Mi
  cpuRequest: "2"
  memRequest: 12000Mi
  xmx: 10g

  monitoringEnabled: true
