image:
  identifier: ${artifact.metadata.image}
  imagePullPolicy: Always

service:
  http:
    externalPort: 8080
    internalPort: 8080

resources:
  cpuLimit: "3"
  memLimit: 8000Mi
  cpuRequest: "2"
  memRequest: 7000Mi
  xmx: 5g
