gcp_project            = "carbon-1287"
gcp_pubsub_project            = "entur-ror-dev"
kube_namespace = "dev"
bucket_marduk_instance_name = "marduk"
bucket_exchange_instance_name = "marduk-exchange"
bucket_otpreport_instance_name = "otpreport-test.entur.org"
location = "europe-west1"
service_account_bucket_role="roles/storage.admin"
