gcp_project = "entur-dev-1287"
gcp_resources_project = "entur-ror-dev"
kube_namespace = "dev"
bucket_marduk_instance_name = "marduk-dev"
bucket_exchange_instance_name = "ror-marduk-exchange-dev"
bucket_graphs_instance_name = "ror-otp-graphs-dev"
bucket_otpreport_instance_name = "otpreport.dev.entur.org"
bucket_nisaba_exchange_instance_name="ror-nisaba-exchange-dev"
service_account_bucket_role = "roles/storage.admin"

