gcp_project = "neon-1287"
gcp_cloudsql_project = "entur-ror-prod"
gcp_pubsub_project = "entur-ror-prod"
kube_namespace = "production"
bucket_marduk_instance_name = "marduk-production"
bucket_exchange_instance_name = "marduk-exchange-production"
bucket_otpreport_instance_name = "otpreport.entur.org"
location = "europe-west1"
service_account_bucket_role = "roles/storage.admin"
db_availability_type = "REGIONAL"

