gcp_project = "entur-1287"
gcp_resources_project = "entur-ror-prod"
kube_namespace = "production"
bucket_marduk_instance_name = "marduk-production"
bucket_exchange_instance_name = "ror-marduk-exchange-production"
bucket_graphs_instance_name = "ror-otp-graphs-production"
bucket_otpreport_instance_name = "otpreport.entur.org"
bucket_nisaba_exchange_instance_name="ror-nisaba-exchange-production"
service_account_bucket_role = "roles/storage.admin"
db_availability = "REGIONAL"

