common:
  env: dev

  ingresses:
    - name : timetable-admin-v1-map
      trafficType: api
      host: timetable-admin-v1-map-gcp2.dev.entur.io
    - name: timetable-admin-v1-timetable
      trafficType: api
      host: timetable-admin-v1-timetable-gcp2.dev.entur.io
sql:
  instance: ent-marduk-dev:europe-west1:marduk-db-pg13=tcp:5432


gcp:
  blobstoreProjectId: ent-marduk-dev
  mardukPubsubProjectId: ent-marduk-dev
  antuPubsubProjectId: ent-antu-dev
  nabuPubsubProjectId: ent-nabu-dev
  bucketName: marduk-dev
  internalBucketName: ror-marduk-internal-dev
  exchangeBucketName: marduk-exchange-dev
  otpReportBucketName: otpreport.dev.entur.org
  otpGraphBucketName: ror-otp-graphs-gcp2-dev
  nisabaExchangeBucketName: ror-nisaba-exchange-dev
  antuExchangeBucketName: ror-antu-exchange-gcp2-dev
  osmSubDirectory: osm

chouette:
  service: http://chouette.dev.entur.internal
  validateLevel1CronSchedule: 0+55+23+?+*+MON-FRI
  refreshStatsCacheCronSchedule: 0+0/10+2-22+*+*+?
  removeOldJobsCronSchedule: 0+15+23+?+*+MON-FRI
  gtfsExport: false
  enablePreValidation: false
  enablePostValidation: false

baba:
  service: http://baba.dev.entur.internal

duplicateFileFilter:
  webFilter: true

netex:
  export: tiamat/CurrentAndFuture_latest.zip

osm:
  fetchCronSchedule: 0+11+*+*+*+?

google:
  publish:
    autoStartup: false
    cronSchedule: 0+0+4+?+*+*
  publishQA:
    autoStartup: false
    cronSchedule: 0+30+4+?+*+*
    includeShapes: true

auth0:
  partner:
    url: https://partner.dev.entur.org
    audience: https://api.dev.entur.io
    administratorAccessEnabled: true
  ror:
    url: https://ror-entur-dev.eu.auth0.com
    audience: https://ror.api.dev.entur.io

oauth2:
  client:
    id: tug4poFyfcqFSXYvJOn7yZCl5FFbIxQM
    url: https://ror-entur-dev.eu.auth0.com/oauth/token
    audience: https://ror.api.dev.entur.io