apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: marduk-service-account
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "marduk.common.labels" . | indent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: marduk-service-account
subjects:
  - kind: ServiceAccount
    name: application
    namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: marduk-service-account
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "marduk.common.labels" . | indent 4 }}
rules:
  - apiGroups: [""] # "" indicates the core API group
    resources: ["services", "pods", "endpoints"]
    verbs: ["get", "watch", "list"]
  - apiGroups: ["batch"]
    resources: ["cronjobs", "jobs"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "watch", "list", "create"]
  - apiGroups: [""]
    resources: ["configmaps"]
    resourceNames: ["marduk-leaders"]
    verbs: ["get", "watch", "list", "update", "patch", "delete"]
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    verbs: ["create", "get", "update", "list"]
