apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
    traffic-type: api
    {{- include "common.labels" . | indent 4 }}
  annotations:
    kubernetes.io/ingress.class: traefik
  name: timetable-admin-v1-map
  namespace: {{ .Release.Namespace }}
spec:
  rules:
  {{- if eq .Values.env "prod"}}
  - host: timetable-admin-v1-map-{{ .Release.Namespace }}.entur.io
  {{ else }}
  - host: timetable-admin-v1-map-{{ .Release.Namespace }}.{{ .Release.Namespace }}.entur.io
  {{- end}}
    http:
      paths:
        - pathType: ImplementationSpecific
          backend:
            service:
              name: {{ template "marduk.name" . }}
              port:
                number: {{ .Values.service.http.externalPort }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
    traffic-type: api
    {{- include "common.labels" . | indent 4 }}
  annotations:
    kubernetes.io/ingress.class: traefik
  name: timetable-admin-v1-timetable
  namespace: {{ .Release.Namespace }}
spec:
  rules:
          {{- if eq .Values.env "prod"}}
    - host: timetable-admin-v1-timetable-{{ .Release.Namespace }}.entur.io
          {{ else }}
    - host: timetable-admin-v1-timetable-{{ .Release.Namespace }}.{{ .Release.Namespace }}.entur.io
            {{- end}}
      http:
        paths:
          - pathType: ImplementationSpecific
            backend:
              service:
                name: {{ template "marduk.name" . }}
                port:
                  number: {{ .Values.service.http.externalPort }}
