apiVersion: v1
kind: ConfigMap
metadata:
  name: marduk-psql-connection
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "marduk.common.labels" . | indent 4 }}
  annotations:
    {{- include "marduk.common.annotations" . | indent 4 }}
data:
  INSTANCES: {{.Values.sql.instance}}
