#!/bin/bash

if [ $# -gt 1 ]; then
    echo "Your command line contains too many ($#) arguments"
    exit 1
elif [ $# == 0 ]; then 
    echo "Your command line contains no arguments"
    exit 1
else 
    echo "Transfering $1"
    scp -i ~/.ssh/lamassu.pem -P 2224 $1 nvdb@localhost:
fi


