-- Requests that are collected and served in one go: several "build the graph" or "export the merged
-- GTFS" messages arriving close together should produce one job, not one job each.
--
-- Replaces a Camel aggregator that held the messages unacknowledged in heap for up to four hours. A row
-- survives a restart, so a batch is no longer lost when the pod running it dies.
--
-- Portable DDL: the tests run this on H2 and the deployments on PostgreSQL, so no bigserial, no uuid
-- column type and no partial index.
CREATE TABLE IF NOT EXISTS batched_request (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kind character varying(64) NOT NULL,
    -- The message that asked for the work, as JSON. Only the newest request's values are used, but the
    -- rest are kept until the batch completes so a failed run can be retried from the same input.
    headers text NOT NULL,
    received_at timestamp without time zone NOT NULL DEFAULT current_timestamp,
    -- Set while a runner is working on this row. Cleared if the run fails, so the next tick picks it up.
    claim_id character varying(36),
    claimed_at timestamp without time zone
);

-- The claim query filters on exactly this pair, and reading a claimed batch filters on claim_id alone.
CREATE INDEX IF NOT EXISTS batched_request_kind_claim_idx ON batched_request (kind, claim_id);
CREATE INDEX IF NOT EXISTS batched_request_claim_idx ON batched_request (claim_id);
